### ISSUE TITLE
FIXME: TypeError: md5() argument 1 must be string or read-only buffer, not bytearray

### ISSUE THREAD

**Issue by ld** [kikyous/xfdown#18]
QQ：******
PASSWD: 
Traceback (most recent call last):
  File "xfdown.py", line 114, in <module>
    xf = XF()
  File "/home/ldong/xfdown/xfdown_api.py", line 171, in **init**
    self.__Login(True)
  File "/home/ldong/xfdown/xfdown_api.py", line 374, in __Login
    self.__verifycode
  File "/home/ldong/xfdown/xfdown_api.py", line 142, in __preprocess
    H = self.__md5(I + verifycode[2])
  File "/home/ldong/xfdown/xfdown_api.py", line 153, in __md5
    return hashlib.md5(item).hexdigest().upper()
TypeError: md5() argument 1 must be string or read-only buffer, not bytearray

**Comment by ld** [comment]
Running Environment: PYTHON2.6
Urwid is installed.

**Comment by shinvdu** [comment]
是上面的环境也有这个问题
