### ISSUE TITLE
登陆不上去

### ISSUE THREAD

**Issue by hsyan2008** [kikyous/xfdown#22]
显示如下，如何解决（我是fedora 17）
PASSWD: 
登录中...
Traceback (most recent call last):
  File "xfdown.py", line 113, in <module>
    xf = XF()
  File "/home/saxon/downloads/xfdown/xfdown_api.py", line 165, in **init**
    self.__Login(True)
  File "/home/saxon/downloads/xfdown/xfdown_api.py", line 376, in __Login
    self.__request_login()
  File "/home/saxon/downloads/xfdown/xfdown_api.py", line 214, in __request_login
    str = self.__request(url = urlv)
  File "/home/saxon/downloads/xfdown/xfdown_api.py", line 174, in __request
    fp=request.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by kikyous** [comment]
看起来像是网络问题

**Comment by hsyan2008** [comment]
但我在chrome里直接登陆没问题啊。。。我在终端下执行就一直报这个
