### ISSUE TITLE
openwrt下无法登陆

### ISSUE THREAD

**Issue by frankmm** [kikyous/xfdown#5]
root@DreamBox:~# python /mnt/sda2/xfdown.py
QQ：1xxxxxxxx
PASSWD: 
Traceback (most recent call last):
  File "/mnt/sda2/xfdown.py", line 445, in <module>
    xf.start()
  File "/mnt/sda2/xfdown.py", line 119, in start
    self.__Login(True)
  File "/mnt/sda2/xfdown.py", line 411, in __Login
    self.__verifycode
  File "/mnt/sda2/xfdown.py", line 85, in __preprocess
    H = self.__md5(I + verifycode[2])
  File "/mnt/sda2/xfdown.py", line 96, in __md5
    return hashlib.md5(item).hexdigest().upper()
TypeError: new() argument 1 must be string or read-only buffer, not bytearray
root@DreamBox:~#

**Comment by frankmm** [comment]
python版本是2.6.4-3

**Comment by nanpuyue** [comment]
me too!
CentOS release 5.5
Python 2.6.8

**Comment by smartmm** [comment]
me too 
centos 6.3
Python 2.6.6

**Comment by finler** [comment]
me too 
debian 6
Python 2.6.6
